export const ADMIN_ROUTE = '/admin'
export const APARTAMENT_ROUTE = '/apartament'
export const REGISTRATION_ROUTE = '/registration'
export const LOGIN_ROUTE = '/login'
export const FAVLIST_ROUTE = '/favorit'
export const DISTRICTS_ROUTE = '/'
export const DISTRICT_ROUTE = '/district'